title: "Shock-AE"
description: "A barebones version of our Spark-AE designed to fit in 1U instead of 2U."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
